import { Drawing } from "../types";

export const getFirstElementId = (index: number): string => {
  return `Element-${index}`;
};

export const createDrawing = (text: string, primaryId: string): Drawing => {
  return {
    elements: [
      {
        type: "rectangle",
        version: 338,
        versionNonce: 2005763643,
        isDeleted: false,
        id: primaryId,
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 578,
        y: 489,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 111.99999999999996,
        height: 79.00000000000003,
        seed: 129174614,
        groupIds: [],
        strokeSharpness: "sharp",
        boundElements: null,
        updated: 1,
        link: null,
      },
      {
        type: "text",
        version: 4,
        versionNonce: 1002402389,
        isDeleted: false,
        id: `${primaryId}-text`,
        fillStyle: "hachure",
        strokeWidth: 1,
        strokeStyle: "solid",
        roughness: 1,
        opacity: 100,
        angle: 0,
        x: 628.5,
        y: 507,
        strokeColor: "#000000",
        backgroundColor: "transparent",
        width: 6,
        height: 45,
        seed: 2029939957,
        groupIds: [],
        strokeSharpness: "sharp",
        boundElements: null,
        updated: 1,
        link: null,
        fontSize: 36,
        fontFamily: 1,
        text,
        baseline: 32,
        textAlign: "center",
        verticalAlign: "middle",
        containerId: null,
        originalText: text,
      },
    ],
    appState: {
      theme: "light",
      collaborators: new Map(),
      currentChartType: "bar",
      currentItemBackgroundColor: "transparent",
      currentItemEndArrowhead: "arrow",
      currentItemFillStyle: "hachure",
      currentItemFontFamily: 1,
      currentItemFontSize: 36,
      currentItemLinearStrokeSharpness: "round",
      currentItemOpacity: 100,
      currentItemRoughness: 1,
      currentItemStartArrowhead: null,
      currentItemStrokeColor: "#000000",
      currentItemStrokeSharpness: "sharp",
      currentItemStrokeStyle: "solid",
      currentItemStrokeWidth: 1,
      currentItemTextAlign: "left",
      cursorButton: "up",
      draggingElement: null,
      editingElement: null,
      editingGroupId: null,
      editingLinearElement: null,
      elementLocked: false,
      elementType: "selection",
      errorMessage: null,
      exportBackground: true,
      exportEmbedScene: false,
      exportWithDarkMode: false,
      fileHandle: null,
      gridSize: null,
      isBindingEnabled: true,
      isLibraryOpen: false,
      isLoading: false,
      isResizing: false,
      isRotating: false,
      lastPointerDownWith: "mouse",
      multiElement: null,
      name: "Untitled-2021-05-08-1402",
      openMenu: null,
      pasteDialog: {
        shown: false,
        data: null,
      },
      previousSelectedElementIds: {},
      resizingElement: null,
      scrolledOutside: false,
      scrollX: -100.5,
      scrollY: -288,
      selectedElementIds: {},
      selectedGroupIds: {},
      selectionElement: null,
      shouldCacheIgnoreZoom: false,
      showHelpDialog: false,
      showStats: false,
      startBoundElement: null,
      suggestedBindings: [],
      toastMessage: null,
      viewBackgroundColor: "#ffffff",
      zenModeEnabled: false,
      zoom: {
        value: 1 as any,
      },
      viewModeEnabled: false,
      offsetLeft: 0,
      offsetTop: 0,
      width: 1312,
      height: 1297,
      exportScale: 1,
      openPopup: null,
      penMode: false,
      penDetected: false,
      pendingImageElement: null,
      showHyperlinkPopup: false,
    },
    files: null,
  };
};

export const createDrawings = (numberOfDrawings: number): Drawing[] => {
  const drawings: Drawing[] = [];
  for (let index = 1; index <= numberOfDrawings; index += 1) {
    drawings.push(createDrawing(index.toString(), getFirstElementId(index)));
  }
  return drawings;
};
