name: Playwright
on: [pull_request]
jobs:
  playwright-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm install
      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium --with-deps
      - name: Build application
        run: pnpm run build
      - name: Run Playwright tests
        run: pnpm run e2e:ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
